#!/bin/sh

# MAC NOTIFICATION ONLY
# this script watches the folder where the output file should be and prints a simple notification when it is DONE
# ACHTUNG: it will print the notification whichever file you change in the directory
# this is used because to parse the whole blockchain can take many hours.
# If you are using mac this gives a convenient Notification on the top, right corner of the screen once the script has finished
# or better, once any file named "output" something is modified in the current folder

# requires the "fswatch" command
# read here how to install it with homebrew
# http://stackoverflow.com/questions/1515730/is-there-a-command-like-watch-or-inotifywait-on-the-mac


# osascript is how you launch an applescript from the terminal
# this is how you talk to the mac only display notification api
# http://apple.stackexchange.com/questions/57412/how-can-i-trigger-a-notification-center-notification-from-an-applescript-or-shel
# https://macosxautomation.com/mavericks/notifications/01.html

# HOW TO RUN
# open the directory where this script is held in the terminal + authorize the script to run and then run it

$ cd path/to/this/script

# copy paste this command, run it and wait.
# Don't close the terminal window or it will stop the watcher
fswatch -o ./output* | xargs -n1 osascript -e 'display notification "SCRIPT DONE" with title "Extra Balance Owners" sound name "Glass"'
